### ISSUE TITLE
Possible update to minecraft 1.21.4

### ISSUE THREAD

**Issue by BrockBoB** [Emirlol/ItemSwap#1]
Hello, I wanted to ask you if you planned to update the mod for Minecraft 1.21.4. I found it really useful but can't used it since the update :/

**Comment by Emirlol** [comment]
It turns out to be working just fine in 1.21.4, so I'll add 1.21.4 as a supported version and release.

I'd also recommend learning about dependency overriding, it helps in situations like this where a new minecraft version doesn't break anything, it's just not listed as supported in the mod's metadata.
